name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        clingo-version: [5.5]

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: conda-forge
    - run: conda --version
    - name: Install dependencies
      run: |
        conda install potassco::clingo=${{ matrix.clingo-version }}.*
        python -m pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
